"""empty message

Revision ID: ac2082fcb6a5
Revises: 
Create Date: 2020-05-09 16:02:25.142960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2082fcb6a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('userpic', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district_street_association',
    sa.Column('District', sa.Integer(), nullable=False),
    sa.Column('Street', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['District'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['Street'], ['streets.id'], )
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_surname', sa.String(), nullable=True),
    sa.Column('client_phone', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('street_volunteer_association',
    sa.Column('Street', sa.Integer(), nullable=False),
    sa.Column('Volunteer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Street'], ['streets.id'], ),
    sa.ForeignKeyConstraint(['Volunteer'], ['volunteers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street_volunteer_association')
    op.drop_table('requests')
    op.drop_table('district_street_association')
    op.drop_table('volunteers')
    op.drop_table('streets')
    op.drop_table('districts')
    # ### end Alembic commands ###
